package clientews.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2025-03-17T18:44:23.049-05:00
 * Generated source version: 4.0.4
 *
 */
@WebServiceClient(name = "ServicioSumarIMPService",
                  wsdlLocation = "http://oscar_alvarez:8080/ServicioSumarIMPService/ServicioSumarIMP?WSDL",
                  targetNamespace = "http://beans/")
public class ServicioSumarIMPService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://beans/", "ServicioSumarIMPService");
    public static final QName ServicioSumarIMPPort = new QName("http://beans/", "ServicioSumarIMPPort");
    static {
        URL url = null;
        try {
            url = new URL("http://oscar_alvarez:8080/ServicioSumarIMPService/ServicioSumarIMP?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServicioSumarIMPService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://oscar_alvarez:8080/ServicioSumarIMPService/ServicioSumarIMP?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public ServicioSumarIMPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicioSumarIMPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioSumarIMPService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServicioSumarIMPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServicioSumarIMPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServicioSumarIMPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ServicioSumarIMP
     */
    @WebEndpoint(name = "ServicioSumarIMPPort")
    public ServicioSumarIMP getServicioSumarIMPPort() {
        return super.getPort(ServicioSumarIMPPort, ServicioSumarIMP.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioSumarIMP
     */
    @WebEndpoint(name = "ServicioSumarIMPPort")
    public ServicioSumarIMP getServicioSumarIMPPort(WebServiceFeature... features) {
        return super.getPort(ServicioSumarIMPPort, ServicioSumarIMP.class, features);
    }

}
